# ============================================================================
# Global Config Options
[global]

# The directory to read/write data
data_dir = "C:\\Workspace\\tmpdb\\Data"

# The directory to load SQL files (views)
sql_dir = "C:\\Workspace\\tmpdb\\.BoltETL\\bolt\\reports\\sql"

# The directory to read/write cached data
cache_dir = "C:\\Workspace\\tmpdb\\Data\\cached"

# The directory to write log files
log_dir = "C:\\Workspace\\tmpdb\\.logs"

# The path to the "data_inventory.json" file
inv_path = "C:\\Workspace\\tmpdb\\Data\\data_inventory.json"

# Coordinate Reference System to reproject spatial data to
crs = "epsg:6515"


# ============================================================================
# Datasources
## See 'DataDefinitions.md' for documentation

[metadata.Parcels]
name = "Parcels"
desc = """Missoula County Parcel Data.
  NOTES:
    Prefer GDB to shapefile to preserve field names."""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\MSL - Missoula Parcels"
filename = "Missoula_Parcels.gdb"
provider = "Montana State Library | Montana Dept of Revenue"
source_url = "http://ftpgeoinfo.msl.mt.gov/Data/Spatial/MSDI/Cadastral/Parcels/Missoula/Missoula_GDB.zip"
load_with_geopandas = true


[metadata.LegislativeDistricts]
name = "LegislativeDistricts"
desc = """Montana's House and Senate districts for 2024-2032"""
source_dir = ""
filename = ""
provider = "Montana State Library"
source_url = "https://ftpgeoinfo.msl.mt.gov/Data/Spatial/MSDI/AdministrativeBoundaries/MontanaLegislativeDistricts_2024_2032_shp.zip"
load_with_geopandas = true


#[metadata.Structures]
#name = "Structures"
#desc = """Montana Structures Framework"""
#source_dir = ""
#filename = ""
#provider = "Montana State Library"
#source_url = "https://ftpgeoinfo.msl.mt.gov/Data/Spatial/MSDI/AddressStructures/StructuresFramework_shp.zip"
#load_with_geopandas = true


[metadata.Townships]
name = "Townships"
#desc = """N/A"""
source_dir = ""
filename = ""
provider = "Montana State Library"
source_url = "https://ftpgeoinfo.msl.mt.gov/Data/Spatial/NonMSDI/Shapefiles/Township1996.zip"
load_with_geopandas = true


[metadata.County4]
name = "County4"
desc = "Missoula County Cadastral Data"
provider = "Montana State Library"
#driver = "ODBC+Driver+17+for+SQL+Server"
#host = "localhost\\SQLEXPRESS"
URI = "mssql+pyodbc://localhost\\SQLEXPRESS/County4?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server"



[metadata.CR0174]
name = "CR0174"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\CR - CR0174"
filename = "*CR-0174*.csv"
provider = "CleverReports"


[metadata.NTDMonthly]
name = "NTDMonthly"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\RCP - NTD Month Report"
filename = "*-NTD_MONTH_REPORT.XLSX"
provider = "RideCheck+"


[metadata.DriverShifts]
name = "DriverShifts"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\Via - Driver Shifts"
filename = "*Driver Shifts*.xlsx"
provider = "Via"


[metadata.RiderAccounts]
name = "RiderAccounts"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\Via - Rider Accounts"
filename = "Rider Account.xlsx"
provider = "Via"


[metadata.RideRequests]
name = "RideRequests"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\Via - Ride Requests"
filename = "*-Ride Requests*.xlsx"
provider = "Via"


[metadata.ViaS10]
name = "ViaS10"
#desc = """N/A"""
source_dir = "C:\\Workspace\\tmpdb\\Data\\raw\\Via - NTD S10"
filename = "*.xlsx"
provider = "Via"
